data:
   - file: "lab2-labor-part1.csv"
     output_folder: "dataframe1"
   - file: "lab2-labor-part2.csv"
     output_folder: "dataframe2"
labels:
   - "duration"
   - "wage-increase-first-year"
   - "wage-increase-second-year"
   - "wage-increase-third-year"
   - "cost-of-living-adjustment"
   - "working-hours"
   - "pension"   
   - "standby-pay"
   - "shift-differential"
   - "statutory-holidays"         
   - "contribution-to-health-plan"
   - "contribution-to-dental-plan"
   - "class"
   - "longterm-disability-assistance"
substitutions: true
calculations: true
creations: true
concatenate_lines: true
print_results: true
