substitutions:
  duration:
     - ["?"]
     - [0]
  wage-increase-first-year:
     - ["?"]
     - [0]
  wage-increase-second-year:
     - ["?"]
     - [0]
  wage-increase-third-year:
     - ["?"]
     - [0]
  cost-of-living-adjustment:
     - ["?", "none", "nnone", "None", "tcf", "tc"]
     - [0  ,      0,       0,      0,     1,    1]
  working-hours:
     - ["?"]
     - [0]
  pension:
  standby-pay:
     - ["?"]
     - [0]
  shift-differential:
     - ["?"]
     - [0]
  statutory-holidays:
     - ["?"]
     - [0]
  vacation:
  contribution-to-dental-plan:
  contribution-to-health-plan:
  class:
