substitutions:
  duration:
     - ["?"]
     - [0]
  wage-increase-first-year:
     - ["?"]
     - [0]
  wage-increase-second-year:
     - ["?"]
     - [0]
  wage-increase-third-year:
     - ["?"]
     - [0]
  cost-of-living-adjustment:
     - ["?", "none", "nnone", "None", "tcf", "tc"]
     - [0  ,      0,       0,      0,     1,    1]
  pension:
     - ["?", "none", "nnone", "None", "empl_contr", "ret_allw"]
     - [0  ,      0,       0,      0,     1,    1]  
  standby-pay:
     - ["?"]
     - [0]
  shift-differential:
     - ["?"]
     - [0]
  statutory-holidays:
     - ["?"]
     - [0]
  contribution-to-dental-plan:
     - ["?", "none", "half", "full"]
     - [0  ,      0,   0.5,    1.0]
  contribution-to-health-plan:
     - ["?", "none", "half", "full"]
     - [0  ,      0,   0.5,    1.0]  
  longterm-disability-assistance:
     - ["?", "none", "missing_value", "yes"]
     - [0  ,      0,       0,         1]    
calculations:
  working-hours:
     - ["?"]
     - ["mode"]
creations:
   total-wage:
     function: "sum_columns"
     columns:
        - "wage-increase-first-year"
        - "wage-increase-second-year"
        - "wage-increase-third-year"
   total-extra-payment:
     function: "sum_columns"
     columns:
        - "shift-differential"
        - "standby-pay"

